blog/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from blog import views
from blog.views import PostViewSet

app_name = "blog"

router = DefaultRouter()
router.register("posts", PostViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    # path("posts.json", views.post_list),
]

myproj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="root.html"), name="root"),
    path("admin/", admin.site.urls),
    path("shop/", include("shop.urls")),
    path("blog/", include("blog.urls")),
    path("news/", include("news.urls")),
    path("discussion/", include("discussion.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from shop.views import review_new, review_list, ReviewViewSet


app_name = "shop"

router = DefaultRouter()
router.register("reviews", ReviewViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("reviews/", review_list, name="review_list"),
    path("reviews/new/", review_new, name="review_new")
]

shop/models.py
from django.core.validators import MaxValueValidator
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Review(TimestampedModel):
    content = models.TextField()
    score = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
        ],
    )

shop/forms.py
from django import forms
from shop.models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"

shop/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from rest_framework import viewsets

from shop.forms import ReviewForm
from shop.models import Review
from shop.serializers import ReviewSerializer

review_list = ListView.as_view(model=Review)

review_new = CreateView.as_view(
    model=Review,
    form_class=ReviewForm,
    success_url=reverse_lazy("shop:review_list")
)


class ReviewViewSet(viewsets.ModelViewSet):
    queryset = Review.objects.all()
    serializer_class = ReviewSerializer

shop/templates/shop/review_form.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Review Form</title>
</head>
<body>
    <h2>Review Form</h2>
    
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit">
    </form>

</body>
</html>

shop/templates/shop/review_list.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Review List</title>
</head>
<body>
    <h1>Review List</h1>

    {% for review in review_list %}
        <div>
        {{ review.content }}
        {{ review.score }}
        </div>
    {% endfor %}

    <hr />
    <a href="{% url "shop:review_new" %}">새 리뷰</a>
</body>
</html>